dist: focal
sudo: required


# Enable C++ support
language: cpp

# Compiler selection
compiler: gcc


# Active branches
branches:
  only:
   - master
   - develop

before_script:
   - mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..

script:
  # Run build commands
  - make
  # execute the text suite
  - test/test_suite -d yes

